<Project>

  <PropertyGroup>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <Version>1.0.0</Version>
    <Authors>StreamDesk Contributors</Authors>
    <Product>StreamDesk</Product>
    <Company>StreamDesk</Company>
    <NeutralLanguage>en-US</NeutralLanguage>
    <AccelerateBuildsInVisualStudio>true</AccelerateBuildsInVisualStudio>
  </PropertyGroup>

</Project>
