<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <RootNamespace>StreamDesk.App</RootNamespace>
    <AssemblyName>StreamDesk</AssemblyName>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>Assets/app-icon.ico</ApplicationIcon>
    
    <AvaloniaUseCompiledBindingsByDefault>false</AvaloniaUseCompiledBindingsByDefault>
    <AssemblyTitle>StreamDesk</AssemblyTitle>
    <InformationalVersion>1.0.0</InformationalVersion>
    <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <SatelliteResourceLanguages>en</SatelliteResourceLanguages>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="11.3.2" />
    <PackageReference Include="Avalonia.Desktop" Version="11.3.2" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="11.3.2" />
    <PackageReference Include="Avalonia.Fonts.Inter" Version="11.3.2" />
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\StreamDesk.Core\StreamDesk.Core.csproj" />
    <ProjectReference Include="..\StreamDesk.Infrastructure\StreamDesk.Infrastructure.csproj" />
    <ProjectReference Include="..\StreamDesk.Application\StreamDesk.Application.csproj" />
    <ProjectReference Include="..\StreamDesk.Providers\StreamDesk.Providers.csproj" />
  </ItemGroup>

  <ItemGroup>
    <AvaloniaResource Include="Assets\**" />
  </ItemGroup>

</Project>
