<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <RootNamespace>StreamDesk.Providers</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\StreamDesk.Application\StreamDesk.Application.csproj" />
  </ItemGroup>

</Project>
